# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: dbyll
google_analytics: dbyll
title: Routehachi
timezone: Japan

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Routehachi

description: Stylish Jekyll Theme
author:
  name: Routehachi
  email: routehachi@urishari.com
  github: routehachi
  twitter: routehachi
  pinterest: 
  linkedin: 
  bio: Bibouroku desu
  email_md5: 

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/fj4l12rxwzi2wgh/silhoette.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
